include("info_work.jl")
f = try
	open("targt.txt")
catch e
	println("文件打开失败")
end
s = read(f,String)
close(f)
# s = "AaAa"
charmx1,charmx2,r1,r2 = genrate()
n11,n12 = regmatch(s,r1)
n21,n22 = regmatch(s,r2)
if sum(n11) == sum(n12)
	n = sum(n11)
	println("总字母数为$n")
else
	error("正则表达式有问题")
	return -1
end
n11 = vec(n11)
# join " "
push!(n11,length(collect(eachmatch(r" ",s))))
charmx1 *= " "
p1 = n11./n
p21 = n21./n
p22 = n22./n
result1 = calcuentropy(p1)
result21 = calcuentropy(p21)
result22 = calcuentropy(p22)
println("第一问：")
print("单字母表达：")
println(charmx1)
print("概率为：")
println(p1)
print("熵H:")
println(result1)
println("双字母表达:")
println(charmx2)
println("覆盖模式概率：")
println(p21)
println("非覆盖模式概率：")
println(p22)
println("覆盖模式下H = $result21")
println("非覆盖模式下H = $result22")
println("第二问：")
xn = xncode(vec(p1),charmx1)
println(xn)
fn = fncode(p1,charmx1)
println(fn)
hfm = hfmcodet(vec(p1),charmx1)
println(hfm)
print("xn平均码长：")
avxn = calculength(xn)
println(avxn)
print("xn编码效率：")
println(calcuefficien(avxn,result1))
print("fn平均码长：")
avfn = calculength(fn)
println(avfn)
print("fn编码效率：")
println(calcuefficien(avfn,result1))
print("hfm平均码长：")
avhfm = calculength(hfm)
println(avhfm)
print("hfm编码效率：")
println(calcuefficien(avhfm,result1))
println("xn编码结果:")
xnec = encode(xn,s)
println(xnec)
println("fn编码结果:")
fnec = encode(fn,s)
println(fnec)
println("hfm编码结果:")
hfmec = encode(hfm,s)
println(hfmec)

#########################
println("第三问")
println("xn译码：")
xnde = decode(xn,xnec)
println(xnde)
println("fn译码：")
fnde = decode(fn,fnec)
println(fnde)
println("hfm译码：")
hfmde = decode(hfm,hfmec)
println(hfmde)